### ISSUE TITLE
Unable to run CozyDrive-3.9.0-x86_64.AppImage - core dumped

### ISSUE THREAD

**Issue by equinton** [cozy-labs/cozy-desktop#1190]
### Description

On my personal computer, I can't execute CozyDrive with a core dumped. 

### Steps to Reproduce

./CozyDrive-3.9.0-x86_64.AppImage 
installed: X-AppImage-BuildId=7c5ff400-8c22-11a8-1d68-075c88fcc75f image: X-AppImage-BuildId=7c5ff400-8c22-11a8-1d68-075c88fcc75f
cozydrive: ../deps/leveldb/leveldb-1.19/db/skiplist.h :344 : void leveldb::SkipList<Key, Comparator>::Insert(const Key&) [with Key = const char*; Comparator = leveldb::MemTable::KeyComparator]:  l'assertion « x == NULL || !Equal(key, x->key) » a échoué.
Abandon (core dumped)

System: 
Linux  4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

[What you expected to happen]

### Actual behavior

[What actually happened]

### Informations

* **reproductible**: [if you do the same steps, does the bug happen always/often/sometimes/only once?] Systematic on this computer, but the software run normally on my business Computer (same OS)
* **OS**: Linux  4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* **version**: [you can find it in the settings tab]

Thanks.

**Comment by equinton** [comment]
New: I have tried to compile cozy-desktop.
/opt/cozy-desktop$ yarn build
yarn run v1.12.3
$ yarn clean
$ rimraf core/lib/ core/tmp/ gui/elm.js gui/app.css* gui/dist/
$ yarn build:css && yarn build:elm && yarn build:tx
$ stylus --sourcemap --compress --use cozy-ui/stylus gui/styles/app.styl --out gui
  compiled gui/app.css
  generated gui/app.css.map
$ elm make ./gui/elm/Main.elm --output ./gui/elm.js
Dependencies loaded from local cache.
Dependencies ready!                
Success! Compiled 26 modules.                                        
$ tx pull --all --minimum-perc=1 || true
/bin/sh: 1: tx: not found
Done in 26.83s.

and with:
/opt/cozy-desktop$ yarn dist
(...)
Packaging for linux x64 using electron 1.8.3 to dist/linux-unpacked
Building AppImage for arch x64
Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /opt/cozy-desktop/node_modules/builder-util/src/util.ts:109:16
    at exithandler (child_process.js:282:5)
    at ChildProcess.errorhandler (child_process.js:294:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at exec (/opt/cozy-desktop/node_modules/builder-util/src/util.ts:77:3)
    at /opt/cozy-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:197:28
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/opt/cozy-desktop/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:245:11)
    at /opt/cozy-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:62:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/opt/cozy-desktop/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:97:11)
    at Lazy.LinuxTargetHelper.iconPromise.Lazy (/opt/cozy-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:19:54)
    at Lazy.get value [as value] (/opt/cozy-desktop/node_modules/lazy-val/src/main.ts:18:23)
    at LinuxTargetHelper.get icons [as icons] (/opt/cozy-desktop/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:27:29)
    at /opt/cozy-desktop/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:145:61
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/opt/cozy-desktop/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at AppImageTarget.copyIcons (/opt/cozy-desktop/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:225:11)
    at /opt/cozy-desktop/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:55:37
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/opt/cozy-desktop/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:191:11)
    at taskManager.addTask.default.map.it (/opt/cozy-desktop/node_modules/electron-builder-lib/src/platformPackager.ts:120:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/opt/cozy-desktop/node_modules/electron-builder-lib/src/platformPackager.ts:120:41)
    at /opt/cozy-desktop/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at LinuxPackager.pack (/opt/cozy-desktop/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /opt/cozy-desktop/node_modules/electron-builder-lib/src/packager.ts:345:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/opt/cozy-desktop/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager.doBuild (/opt/cozy-desktop/node_modules/electron-builder-lib/out/packager.js:407:11)
    at /opt/cozy-desktop/node_modules/electron-builder-lib/src/packager.ts:289:52
From previous event:
    at Packager._build (/opt/cozy-desktop/node_modules/electron-builder-lib/out/packager.js:351:11)
    at /opt/cozy-desktop/node_modules/electron-builder-lib/src/packager.ts:259:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (/opt/cozy-desktop/node_modules/electron-builder-lib/out/packager.js:311:11)
    at /opt/cozy-desktop/node_modules/electron-builder/src/builder.ts:287:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/opt/cozy-desktop/node_modules/electron-builder/out/builder.js:61:21)
    at build (/opt/cozy-desktop/node_modules/electron-builder/src/builder.ts:257:10)
    at then (/opt/cozy-desktop/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.args [as handler] (/opt/cozy-desktop/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/opt/cozy-desktop/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/opt/cozy-desktop/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/opt/cozy-desktop/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/opt/cozy-desktop/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.

If I try to run:
/opt/cozy-desktop/dist/linux-unpacked$ ./cozydrive 
pt/cozy-desktop/dist/linux-unpacked/cozydrive: ../deps/leveldb/leveldb-1.20/db/skiplist.h :344 : void leveldb::SkipList<Key, Comparator>::Insert(const Key&) [with Key = const char*; Comparator = leveldb::MemTable::KeyComparator]:  l'assertion « x == __null || !Equal(key, x->key) » a échoué.
Abandon (core dumped)

It's the same behavior.

**Comment by taratatach** [comment]
Hi @equinton. Seems like you're running into this issue: https://github.com/SimulatedGREG/electron-vue/issues/130

Basically, you're missing the `icns2png` executable. The link above says you can install it with ` sudo apt install icnsutils`.

**Comment by equinton** [comment]
I have installed icnsutils, but the problem is not resolved:
which icns2png
/usr/bin/icns2png
eric@maison:~/Téléchargements$ ./CozyDrive-3.11.1-x86_64.AppImage 
installed: X-AppImage-BuildId=449aa840-02a0-11a9-14c5-b7f4dd104933 image: X-AppImage-BuildId=449aa840-02a0-11a9-14c5-b7f4dd104933
cozydrive: ../deps/leveldb/leveldb-1.20/db/skiplist.h :344 : void leveldb::SkipList<Key, Comparator>::Insert(const Key&) [with Key = const char*; Comparator = leveldb::MemTable::KeyComparator]:  l'assertion « x == __null || !Equal(key, x->key) » a échoué.
Abandon (core dumped)

thanks,

**Comment by taratatach** [comment]
A similar issue was reported on `leveldb`'s repository a while ago: https://github.com/Level/leveldown/issues/315

We'll have to reach out to them and see if they have any idea what could cause this.
In the meantime, could you clear your dependencies and try installing them again? Maybe recompiling `leveldb` would help.

**Comment by equinton** [comment]
It's ok now: I deleted the database in ~/.cozy-desktop (rm -Rf db*), and reload cozy.
