### ISSUE TITLE
Electron 3.0 support

### ISSUE THREAD

**Issue by ArchangeGabriel** [cozy-labs/cozy-desktop#1291]
### Description

I’ve tried to build cozy-desktop with electron 3.0, but upon launching cozy-desktop afterwards nothing happens. Electron 2.x is already EOL, so this should be done quickly.

### Steps to Reproduce

1. Build with electron 3.x.
2. Try to launch.

### Expected behavior

It works.

### Actual behavior

No window appears.

### Informations

* **reproductible**: 100%
* **OS**: ArchLinux
* **version**: 3.10.2

**Comment by sebn** [comment]
Hello @ArchangeGabriel, thank you for trying it, we didn't have the time to do so yet.
The upgrade is not planned for the current iteration, but should be done in the next one (starting in two weeks).

**Comment by ArchangeGabriel** [comment]
I was pointed to the existence of a log, which actually contains an error:
```
{"name":"Cozy Desktop","hostname":"sappcw63","pid":28520,"component":"GUI","level":50,"err":{"message":"Cannot create property 'recursive' on number '2'","name":"TypeError","stack":"TypeError: Cannot create property 'recursive' on number '2'\n    at Object.copySync (/usr/lib/cozy-desktop/resources/app.asar/node_modules/fs-extra/lib/copy-sync/copy-sync.js:14:21)\n    at Config._moveTmpConfig (/usr/lib/cozy-desktop/resources/app.asar/core/config.js:75:8)\n    at Config.read (/usr/lib/cozy-desktop/resources/app.asar/core/config.js:48:14)\n    at new Config (/usr/lib/cozy-desktop/resources/app.asar/core/config.js:24:24)\n    at new App (/usr/lib/cozy-desktop/resources/app.asar/core/app.js:66:19)\n    at setupProxy (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:312:17)\n    at module.exports (/usr/lib/cozy-desktop/resources/app.asar/gui/js/proxy.js:108:10)\n    at App.app.on (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:308:3)\n    at App.emit (events.js:187:15)\n    at App.EventEmitter.emit (domain.js:442:20)\n    at App.topLevelDomainCallback (domain.js:121:23)"},"msg":"Cannot create property 'recursive' on number '2'","time":"2018-11-22T21:29:12.374Z","v":0}
```

**Comment by ArchangeGabriel** [comment]
So, that gets it to the next issues (though now the GUI actually appears):
```
{"name":"Cozy Desktop","hostname":"<hostname>","pid":32136,"component":"GUI:autoupdater","level":50,"msg":"Error: Error: ENOENT, dev-app-update.yml not found in /usr/lib/cozy-desktop/resources/app.asar\n    at notFoundError (ELECTRON_ASAR.js:108:19)\n    at fs.readFile (ELECTRON_ASAR.js:536:16)\n    at go$readFile (/usr/lib/cozy-desktop/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:73:14)\n    at readFile (/usr/lib/cozy-desktop/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:70:12)\n    at readFile (/usr/lib/cozy-desktop/resources/app.asar/node_modules/universalify/index.js:5:67)\nFrom previous event:\n    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27\n    at Generator.next (<anonymous>)\nFrom previous event:\n    at AppImageUpdater.loadUpdateConfig (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)\n    at Lazy.AppUpdater.configOnDisk.Lazy (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)\n    at Lazy.get value [as value] (/usr/lib/cozy-desktop/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)\n    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46\n    at Generator.next (<anonymous>)\nFrom previous event:\n    at AppImageUpdater.doCheckForUpdates (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)\n    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25\n    at Generator.next (<anonymous>)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\n    at process.topLevelDomainCallback (domain.js:121:23)\nFrom previous event:\n    at AppImageUpdater._checkForUpdates (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)\n    at AppImageUpdater.checkForUpdates (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)\n    at UpdaterWM.checkForUpdates (/usr/lib/cozy-desktop/resources/app.asar/gui/js/updater.window.js:91:17)\n    at setupProxy (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:341:19)\n    at module.exports (/usr/lib/cozy-desktop/resources/app.asar/gui/js/proxy.js:108:10)\n    at App.app.on (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:308:3)\n    at App.emit (events.js:187:15)\n    at App.EventEmitter.emit (domain.js:442:20)\n    at App.topLevelDomainCallback (domain.js:121:23)","time":"2018-11-24T19:59:23.834Z","v":0}
{"name":"Cozy Desktop","hostname":"<hostname>","pid":32136,"component":"GUI:autoupdater","level":50,"err":{"message":"ENOENT, dev-app-update.yml not found in /usr/lib/cozy-desktop/resources/app.asar","name":"Error","stack":"Error: ENOENT, dev-app-update.yml not found in /usr/lib/cozy-desktop/resources/app.asar\n    at notFoundError (ELECTRON_ASAR.js:108:19)\n    at fs.readFile (ELECTRON_ASAR.js:536:16)\n    at go$readFile (/usr/lib/cozy-desktop/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:73:14)\n    at readFile (/usr/lib/cozy-desktop/resources/app.asar/node_modules/graceful-fs/graceful-fs.js:70:12)\n    at readFile (/usr/lib/cozy-desktop/resources/app.asar/node_modules/universalify/index.js:5:67)\nFrom previous event:\n    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27\n    at Generator.next (<anonymous>)\nFrom previous event:\n    at AppImageUpdater.loadUpdateConfig (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)\n    at Lazy.AppUpdater.configOnDisk.Lazy (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)\n    at Lazy.get value [as value] (/usr/lib/cozy-desktop/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)\n    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46\n    at Generator.next (<anonymous>)\nFrom previous event:\n    at AppImageUpdater.doCheckForUpdates (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)\n    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25\n    at Generator.next (<anonymous>)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\n    at process.topLevelDomainCallback (domain.js:121:23)\nFrom previous event:\n    at AppImageUpdater._checkForUpdates (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)\n    at AppImageUpdater.checkForUpdates (/usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)\n    at UpdaterWM.checkForUpdates (/usr/lib/cozy-desktop/resources/app.asar/gui/js/updater.window.js:91:17)\n    at setupProxy (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:341:19)\n    at module.exports (/usr/lib/cozy-desktop/resources/app.asar/gui/js/proxy.js:108:10)\n    at App.app.on (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:308:3)\n    at App.emit (events.js:187:15)\n    at App.EventEmitter.emit (domain.js:442:20)\n    at App.topLevelDomainCallback (domain.js:121:23)","code":"ENOENT"},"msg":"Error in auto-updater! ","time":"2018-11-24T19:59:23.834Z","v":0}
```
And a bit latter:
```
{"name":"Cozy Desktop","hostname":"<hostname>","pid":32136,"component":"GUI/TRAY","level":50,"err":{"message":"Uncaught Error: Trying to send an unexpected type of value through port `diskSpace`:\nExpecting an object with a field named `quota` but instead got: {\"used\":1635798824}","stack":"Error: Trying to send an unexpected type of value through port `diskSpace`:\nExpecting an object with a field named `quota` but instead got: {\"used\":1635798824}\n    at Object.send (/usr/lib/cozy-desktop/resources/app.asar/gui/elm.js:2827:10)\n    at EventEmitter.ipcRenderer.on (file:///usr/lib/cozy-desktop/resources/app.asar/gui/ports.js:172:29)\n    at EventEmitter.emit (events.js:182:13)"},"msg":"Uncaught Error: Trying to send an unexpected type of value through port `diskSpace`:\nExpecting an object with a field named `quota` but instead got: {\"used\":1635798824}","time":"2018-11-24T19:59:27.582Z","v":0}
```

Note that there is another issue though, printed on the terminal for that one as well as in a Cozy Drive notification, that might not be fixable until you move to nodejs 10.x I guess:
```
Unhandled rejection Error: Error: The module '/tmp/.org.chromium.Chromium.5sWItp'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).: unable to import leveldown
    at requireLeveldown (/usr/lib/cozy-desktop/resources/app.asar/node_modules/pouchdb/lib/index.js:6200:12)
    at PouchDB$5.LevelDownPouch (/usr/lib/cozy-desktop/resources/app.asar/node_modules/pouchdb/lib/index.js:6400:17)
    at new PouchDB$5 (/usr/lib/cozy-desktop/resources/app.asar/node_modules/pouchdb/lib/index.js:2682:36)
    at new Pouch (/usr/lib/cozy-desktop/resources/app.asar/core/pouch.js:46:15)
    at new App (/usr/lib/cozy-desktop/resources/app.asar/core/app.js:67:18)
    at setupProxy (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:312:17)
    at module.exports (/usr/lib/cozy-desktop/resources/app.asar/gui/js/proxy.js:108:10)
    at App.app.on (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:308:3)
    at App.emit (events.js:187:15)
    at App.EventEmitter.emit (domain.js:442:20)
    at App.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at PouchDB$5.<anonymous> (/usr/lib/cozy-desktop/resources/app.asar/node_modules/pouchdb/lib/index.js:118:19)
    at PouchDB$5.get (/usr/lib/cozy-desktop/resources/app.asar/node_modules/argsarray/index.js:14:18)
    at Pouch.createDesignDoc (/usr/lib/cozy-desktop/resources/app.asar/core/pouch.js:310:13)
    at Pouch.addByPathView (/usr/lib/cozy-desktop/resources/app.asar/core/pouch.js:272:17)
    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/async/dist/async.js:3866:24
    at replenish (/usr/lib/cozy-desktop/resources/app.asar/node_modules/async/dist/async.js:998:17)
    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/usr/lib/cozy-desktop/resources/app.asar/node_modules/async/dist/async.js:1027:24)
    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/async/dist/async.js:1032:16
    at _parallel (/usr/lib/cozy-desktop/resources/app.asar/node_modules/async/dist/async.js:3865:5)
    at Object.series (/usr/lib/cozy-desktop/resources/app.asar/node_modules/async/dist/async.js:4721:5)
    at Pouch.addAllViews (/usr/lib/cozy-desktop/resources/app.asar/core/pouch.js:251:18)
    at Sync.start (/usr/lib/cozy-desktop/resources/app.asar/core/sync.js:97:22)
    at App.startSync (/usr/lib/cozy-desktop/resources/app.asar/core/app.js:278:22)
    at App.synchronize (/usr/lib/cozy-desktop/resources/app.asar/core/app.js:300:17)
    at startSync (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:264:13)
    at showWindowStartApp (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:60:5)
    at updaterWindow.onUpToDate (/usr/lib/cozy-desktop/resources/app.asar/gui/main.js:339:7)
    at UpdaterWM.afterUpToDate (/usr/lib/cozy-desktop/resources/app.asar/gui/js/updater.window.js:75:7)
    at AppImageUpdater.UpdaterWM.autoUpdater.on (/usr/lib/cozy-desktop/resources/app.asar/gui/js/updater.window.js:44:12)
    at AppImageUpdater.emit (events.js:187:15)
    at AppImageUpdater.EventEmitter.emit (domain.js:442:20)
    at /usr/lib/cozy-desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:267:12
    at Generator.throw (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by nono** [comment]
@ArchangeGabriel are you using electron-builder for your tests? It should take care to recompile the node modules with the node embedded in electron.

**Comment by ArchangeGabriel** [comment]
I’m just running `yarn dist --dir`, no electron-builder. I’m not sure if and how I should be using electron-builder.

**Comment by nono** [comment]
`yarn dist` calls electron-builder, cf https://github.com/cozy-labs/cozy-desktop/blob/master/package.json#L42

**Comment by ArchangeGabriel** [comment]
Right, but it seems to download a very old electron version (1.8.3 or something like that) to do so. I’ll get a full build log later today and link it here.

**Comment by ArchangeGabriel** [comment]
Here we go:
```
==> Starting prepare()...
patching file core/config.js
yarn install v1.12.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.1.1: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > cozy-client-js@0.7.1" has unmet peer dependency "babel-polyfill@^6.26.0".
warning " > cozy-ui@3.0.0-beta39" has unmet peer dependency "piwik-react-router@^0.8.2".
[5/5] Building fresh packages...
Done in 102.27s.
==> Starting build()...
yarn run v1.12.3
$ yarn clean
$ rimraf core/lib/ core/tmp/ gui/elm.js gui/app.css* gui/dist/
$ yarn build:css && yarn build:elm && yarn build:tx
$ stylus --sourcemap --compress --use cozy-ui/stylus gui/styles/app.styl --out gui
  generated gui/app.css.map
  compiled gui/app.css
$ elm make ./gui/elm/Main.elm --output ./gui/elm.js
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 5.1.1
    elm-lang/html 2.0.0
    elm-lang/http 1.0.0
    elm-lang/svg 2.0.0
    elm-lang/virtual-dom 2.0.4
    sporto/erl 13.0.2

Do you approve of this plan? [Y/n] Y
Starting downloads...

  ● elm-lang/html 2.0.0
  ● elm-lang/svg 2.0.0
  ● elm-lang/virtual-dom 2.0.4
  ● elm-lang/core 5.1.1
  ● sporto/erl 13.0.2
  ● elm-lang/http 1.0.0

Packages configured successfully!
Success! Compiled 74 modules.
Successfully generated ./gui/elm.js
$ tx pull --all --minimum-perc=1 || true
/bin/sh: tx: command not found
Done in 17.88s.
==> Entering fakeroot environment...
==> Starting package()...
yarn run v1.12.3
$ electron-builder build --dir
electron-builder 19.49.0
Using electron-builder.yml configuration file
Rebuilding native production dependencies for linux:x64
Rebuilding native dependency dtrace-provider
Rebuilding native dependency leveldown
Packaging for linux x64 using electron 1.8.3 to dist/linux-unpacked
Downloading tmp-2954-1-SHASUMS256.txt-1.8.3
[============================================>] 100.0% of 3.43 kB (3.43 kB/s)
Done in 103.69s.
```
I think the issue is this last part where it downloads this old electron version (system electron is 3.0.9).

**Comment by ArchangeGabriel** [comment]
Upgrading to `electron 2.0.14` (in `package.json`) results in the same issue. Upgrading to a 3.x version results in a failure to build because this requires building with NodeJS 10.x (see https://github.com/cozy-labs/cozy-desktop/issues/1054).

The build log is a bit more explicit this time: https://gist.github.com/ArchangeGabriel/ae4ea93ff848b9e5a8aeb92b8cdfbc46

From what I remember, this is an issue with the `nan` module not being compatible with NodeJS 10.x because of removed v8 symbols (version up to 2.3.0 at least, while 2.9.0 is OK). According to `yarn.lock`, it appears several times in the tree, so you have a bunch of dependency to update. This goes far beyond simple patching, so I’ll stop here and leave you handle this nice NodeJS dependency nightmare. ;)

**Comment by ArchangeGabriel** [comment]
So for now I ended up packaging `electron2` as `electron 2.0.14` in our repos and using it for cozy-desktop, but a migration to `electron 3.x` in the next iteration would be very welcome. ;)

**Comment by ArchangeGabriel** [comment]
If you can jump directly to `electron 4` that has recently been released, that would be even better. ;)

**Comment by ArchangeGabriel** [comment]
I’ve just seen that [you upgraded from 1.8.3 to 2.0.18](https://github.com/cozy-labs/cozy-desktop/pull/1515), but now Electron 2.x is EOL since 5.0 was released two days ago. So you are up-to-date regarding security issues currently, but it’s going to not be the case very soon (if not already). Are there any further plans to upgrade to newer versions?

**Comment by sebn** [comment]
Yes, we'd like to upgrade quickly to electron 3 at least.
But since upgrade issues [may happen](https://github.com/cozy-labs/cozy-desktop/pull/1566), we can't commit to a date yet :)

**Comment by taratatach** [comment]
I'm closing this since we've moved to Electron v5. Thanks for your efforts @ArchangeGabriel, sorry we didn't make the upgrade sooner.
We'll try to stay more up-to-date with Electron from now on.
