### ISSUE TITLE
La synchronization ne démarre jamais et electron ne fourni pas d'erreur

### ISSUE THREAD

**Issue by encolpe** [cozy-labs/cozy-desktop#2088]
### Description

Le client commence une synchronisation, échoue une première fois et ensuite refuse de démarrer

### Steps to Reproduce
```
$ /home/encolpe/.local/lib/cozycloud/Cozy-Drive-3.28.0-beta.1-x86_64.AppImage 
FAIL TO SETUP TypeError: reporter.getCrashesDirectory is not a function
    at MainBackend.installNativeHandler (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:164:43)
    at MainBackend.install (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:76:28)
    at MainClient.BaseClient.install (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/node_modules/@sentry/core/dist/baseclient.js:87:21)
    at Object.initAndBind (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/node_modules/@sentry/core/dist/sdk.js:19:12)
    at Object.init (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/node_modules/@sentry/electron/dist/main/index.js:32:12)
    at Object.specificInit (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/node_modules/@sentry/electron/dist/dispatch.js:137:74)
    at Object.init (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/node_modules/@sentry/electron/dist/sdk.js:52:16)
    at Object.setup (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/core/utils/sentry.js:57:12)
    at App.setup (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/core/app.js:359:12)
    at setupDesktop (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/gui/main.js:87:19)
    at App.<anonymous> (/tmp/.mount_Cozy-D21l6yE/resources/app.asar/gui/main.js:540:11)
```

### Expected behavior

Avoir une véritable erreur, savoir ce qui manque dans la config ou le fichier qui pose problème.

### Informations

* **reproductible**: depuis plusieurs mois
* **OS**: KUnbuntu 20.04
* **version**: 3.26, 3.27, 3.28 beta1

**Comment by encolpe** [comment]
En lançant l'environnement de dev avec `COZY_NO_SENTRY=true yarn start`, le message d'erreur disparait.

En revanche toujours pas de synchronisation.

**Comment by taratatach** [comment]
Cette erreur est connue, est effectivement liée à Sentry et ne pose pas problème pour la synchronisation.
Les erreurs de synchronisation seront visibles dans les logs que vous pouvez trouver dans `~/.coxy-desktop/logs.txt*`.
