### ISSUE TITLE
Appimage throws error during run time and fails to start

### ISSUE THREAD

**Issue by 72siddharth** [cozy-labs/cozy-desktop#2093]
### Description

When executing the appimage from the terminal some error message is printed and the gui doesn't appear.
I tried both the official app image and also compiling it from source. This is what gets printed:
```
FAIL TO SETUP TypeError: reporter.getCrashesDirectory is not a function
    at MainBackend.installNativeHandler (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:164:43)
    at MainBackend.install (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:76:28)
    at MainClient.BaseClient.install (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/node_modules/@sentry/core/dist/baseclient.js:87:21)
    at Object.initAndBind (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/node_modules/@sentry/core/dist/sdk.js:19:12)
    at Object.init (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/node_modules/@sentry/electron/dist/main/index.js:32:12)
    at Object.specificInit (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/node_modules/@sentry/electron/dist/dispatch.js:137:74)
    at Object.init (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/node_modules/@sentry/electron/dist/sdk.js:52:16)
    at Object.setup (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/core/utils/sentry.js:57:12)
    at App.setup (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/core/app.js:359:12)
    at setupDesktop (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/gui/main.js:89:19)
    at App.<anonymous> (/tmp/.mount_Cozy-DeBf1Cr/resources/app.asar/gui/main.js:552:11)
```

### Steps to Reproduce

1. Make the app image executable
2. Execute the app image from the terminal

### Expected behavior

The cozy-desktop gui appears

### Actual behavior

An error message is printed and the cozy-desktop gui does not appear

### Informations

* **reproductible**: everytime I run the appimage
* **OS**: Garuda Linux - 5.12.2-zen2-1-zen
* **version**: cozy-desktop-3.27.0-x86_64

**Comment by shulard** [comment]
Hello !

I've the same error on my side since a few weeks. I'm not able to run Cozy on my Linux laptop anymore.

**Comment by taratatach** [comment]
Hi @72siddharth, thank you for reporting your issue.

This message is merely a consequence of the crash though and does not give us information about what went wrong.
I suggest you write an e-mail to `support [at] cozycloud.cc` with your Cozy Desktop logs attached so we can analyze them.
You can find them in the `~/.cozy-desktop` folder (files named `logs…`).

@shulard I suggest you do the same as there can be many reasons why your app is crashing.
