### ISSUE TITLE
`GLIBC_2.32' not found error in Mar 10 Cozy-Drive-3.37.0-x86_64.AppImage

### ISSUE THREAD

**Issue by dooleysworne** [cozy-labs/cozy-desktop#2283]
### Description

`GLIBC_2.32' not found error in Mar 10 Cozy-Drive-3.37.0-x86_64.AppImage

### Machine
Kernel: 5.15.0-67-generic x86_64 bits: 64 Desktop: MATE 1.24.0 Distro: Ubuntu 20.04.5 LTS (Focal Fossa) 

### Full Error Output

$ ./Cozy-Drive-3.37.0-x86_64.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Cozy-DRXjVrv/resources/app.asar.unpacked/node_modules/@parcel/watcher/build/Release/watcher.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at load (/tmp/.mount_Cozy-DRXjVrv/resources/app.asar/node_modules/node-gyp-build/index.js:22:10)
    at Object.<anonymous> (/tmp/.mount_Cozy-DRXjVrv/resources/app.asar/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed

**Comment by taratatach** [comment]
Hi,

thanks for reporting this message. We've upgraded Electron and it appears your system does not have the newly required glibc version 2.32.
Have you witnessed any issue with the app's behavior besides seeing this message in your terminal?

**Comment by dooleysworne** [comment]
Thanks for the response. I suspected as such. The Cozy Drive desktop app didn't load after trying to update this morning. That's why I tried loading it from the terminal.

**Comment by howetuft** [comment]
Hello,

The same goes for me...

**System**
Xubuntu 20.04.5 LTS
5.15.0-67-generic

**Error message**
```
$ AppImageLauncher Cozy-Drive-3.37.0-x86_64.AppImage

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Cozy-DNTbE7x/resources/app.asar.unpacked/node_modules/@parcel/watcher/build/Release/watcher.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at load (/tmp/.mount_Cozy-DNTbE7x/resources/app.asar/node_modules/node-gyp-build/index.js:22:10)
    at Object.<anonymous> (/tmp/.mount_Cozy-DNTbE7x/resources/app.asar/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0


```

**Comment by dooleysworne** [comment]
Give this a try . . .

**$ sudo apt install glibc-source**

Then grab the latest *.AppImage from https://github.com/cozy-labs/cozy-desktop/releases
Make it executable and launch it.

(To remove . . .)
**$ sudo apt purge glibc-source**

**Comment by dooleysworne** [comment]
Hmmm . . .
After doing the apt install of glibc-source . . .

**$ ldd --version**
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

Error message . . .
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found

Evidently my version of Ubuntu is just slightly behind in the glibc package installation department.

What's interesting is that I have two other laptops with Cozy Drive on them (both Ubuntu) and have had no problems with the latest Cozy Drive updates.

My problem device has the following inxi output . . .

**$ inxi -F**
System:
  Host: MD-latitudee6430 Kernel: 5.15.0-67-generic x86_64 bits: 64 
  Desktop: MATE 1.24.0 Distro: Ubuntu 20.04.5 LTS (Focal Fossa) 
Machine:
  Type: Laptop System: Dell product: Latitude E6430 v: 01 
  serial: <superuser/root required> 
  Mobo: Dell model: 0H3MT5 v: A00 serial: <superuser/root required> 
  BIOS: Dell v: A18 date: 01/18/2016 
Battery:
  ID-1: BAT0 charge: 0% condition: 35.5/62.2 Wh (57%) 
CPU:
  Topology: Dual Core model: Intel Core i7-3520M bits: 64 type: MT MCP 
  L2 cache: 4096 KiB 
  Speed: 1012 MHz min/max: 1200/3600 MHz Core speeds (MHz): 1: 1012 2: 1314 
  3: 1206 4: 1039 
Graphics:
  Device-1: Intel 3rd Gen Core processor Graphics driver: i915 v: kernel 
  Device-2: NVIDIA GF108GLM [NVS 5200M] driver: nouveau v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: modesetting 
  unloaded: fbdev,vesa resolution: 1600x900~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) 
  v: 4.2 Mesa 21.2.6 
Audio:
  Device-1: Intel 7 Series/C216 Family High Definition Audio 
  driver: snd_hda_intel 
  Device-2: NVIDIA GF108 High Definition Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.15.0-67-generic 
Network:
  Device-1: Intel 82579LM Gigabit Network driver: e1000e 
  IF: eno1 state: down mac: -- (removed)
  Device-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi 
  IF: wlp3s0 state: up mac: -- (removed)
Drives:
  Local Storage: total: 698.64 GiB used: 133.24 GiB (19.1%) 
  ID-1: /dev/sda vendor: Western Digital model: WD7500BPKT-75PK4T0 
  size: 698.64 GiB 
RAID:
  Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci 
Partition:
  ID-1: / size: 686.11 GiB used: 133.24 GiB (19.4%) fs: ext4 dev: /dev/sda5 
Sensors:
  System Temperatures: cpu: 48.0 C mobo: 42.0 C sodimm: 36.0 C gpu: nouveau 
  temp: 49 C 
  Fan Speeds (RPM): cpu: 0 
Info:
  Processes: 234 Uptime: 37m Memory: 7.67 GiB used: 1.53 GiB (20.0%) 
  Shell: bash inxi: 3.0.38

**Comment by dooleysworne** [comment]
My solution was to upgrade from Ubuntu 20.04 LTS to 22.04 LTS.

**Comment by J-F** [comment]
Same issue on Debian stable ... Sorry, but i didn't plan to switch on Debian Testing.

**Comment by taratatach** [comment]
Hi! Sorry to see this is affecting a lot of people.

We ran a test build to try and fix this situation. Could you try this version and give us your feedback please? https://claudecozy-drive.mycozy.cloud/public?sharecode=5T0dzNhjTyaX#/folder/cc2d019bf9269f7f552e6a0baadcd392

**Comment by taratatach** [comment]
This issue should be fixed in https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.38.0-beta.1

**Comment by J-F** [comment]
The [v3.38.0-beta.1] version works fine on debian.
Thank you very much

**Comment by howetuft** [comment]
Works for me as well (Xubuntu 20.04.5 LTS).
Thank you!
