### ISSUE TITLE
`version `GLIBC_2.32' not found` with version 3.37.0 on Ubuntu 20.04

### ISSUE THREAD

**Issue by regisss** [cozy-labs/cozy-desktop#2299]
### Description

I cannot execute the AppImage `Cozy-Drive-3.37.0-x86_64.AppImage` on Ubuntu 20.04 because of an issue with the version of glibc.

### Steps to Reproduce

1. Execute `Cozy-Drive-3.37.0-x86_64.AppImage` on Ubuntu 20.04

### Expected behavior

I would expect it to work on Ubuntu 20.04 since it's not such an old version.

### Actual behavior

The full error message I got:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Cozy-Dx6hUCT/resources/app.asar.unpacked/node_modules/@parcel/watcher/build/Release/watcher.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at load (/tmp/.mount_Cozy-Dx6hUCT/resources/app.asar/node_modules/node-gyp-build/index.js:22:10)
    at Object.<anonymous> (/tmp/.mount_Cozy-Dx6hUCT/resources/app.asar/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
```

### Informations

* **reproductible**: it always happens when I run the AppImage
* **OS**: Ubuntu 20.04.6 LTS
* **version**: 3.37.0

**Comment by taratatach** [comment]
Hi @regisss.

This is a known issue of version 3.37.0. Please update to [v3.38.0](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.38.0) which fixes it.

**Comment by regisss** [comment]
Great!
