### ISSUE TITLE
Error while trying to sync my files

### ISSUE THREAD

**Issue by frankrousseau** [cozy-labs/cozy-desktop#269]
Hello,

 I tried to use Cozy Desktop with my Cozy. Registration worked fine but syncing failed. Here is the stacktrace: 

```
[2016-04-05 15:47:58:825] info - Local watcher  | Start watching filesystem for changes
[2016-04-05 15:48:09:363] error - Remote watcher | An error occured copying database
[2016-04-05 15:48:09:363] error - Remote watcher | An error occured copying database
[2016-04-05 15:48:09:368] error - Remote watcher | Error: ETIMEDOUT
    at onError (/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/lib/index.js:2597:18)
    at Request._callback (/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/lib/index.js:2635:14)
    at self.callback (/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at null._onTimeout (/usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/node_modules/request/request.js:765:12)
    at Timer.listOnTimeout (timers.js:92:15)
```

Any idea about where the problem comes from?

**Comment by nono** [comment]
Hi, do you have some logs for the proxy and data-system?

**Comment by nono** [comment]
The error happened when cozy-desktop was copying the metadata about files and folders from the remote cozy.

**Comment by frankrousseau** [comment]
It looks like my Cozy was not working properly. I updated everything and now I have other kind of messages:

```
[2016-04-05 17:39:25:524] error - Remote watcher | Invalid id
[2016-04-05 17:39:25:524] error - Remote watcher | Invalid id
[2016-04-05 17:39:25:525] error - Remote watcher | {"path":".","docType":"file","remote":{"_id":"EB8E29EC-0583-F9A7-8F4B-F20AE3B0370A","_rev":"3-fa44c4e0c97e56ece2473474b285deaa","binary":{"_id":"EA9368E4-C3A8-3020-AF76-6237D69D9679","_rev":"2-7f589fae648615b598a43b3ee0348de7"}}}
[2016-04-05 17:39:25:525] error - Remote watcher | {"path":".","docType":"file","remote":{"_id":"EB8E29EC-0583-F9A7-8F4B-F20AE3B0370A","_rev":"3-fa44c4e0c97e56ece2473474b285deaa","binary":{"_id":"EA9368E4-C3A8-3020-AF76-6237D69D9679","_rev":"2-7f589fae648615b598a43b3ee0348de7"}}}
[2016-04-05 17:39:25:525] error - Remote watcher | Failed to copy one doc
[2016-04-05 17:39:25:525] error - Remote watcher | Failed to copy one doc
[2016-04-05 17:39:25:525] error - Remote watcher | Error: Invalid path/name
    at RemoteWatcher.putDoc (/usr/local/lib/node_modules/cozy-desktop/lib/remote/watcher.js:227:25)
    at RemoteWatcher.putDoc (/usr/local/lib/node_modules/cozy-desktop/lib/remote/watcher.js:4:59)
    at /usr/local/lib/node_modules/cozy-desktop/lib/remote/watcher.js:182:26
    at /usr/local/lib/node_modules/cozy-desktop/lib/pouch.js:159:18
    at /usr/local/lib/node_modules/cozy-desktop/node_modules/pouchdb/lib/index.js:5014:9
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[2016-04-05 17:39:25:525] error - Remote watcher | Error: Invalid path/name
```

I have a lot of legacy data. It's probably related to that.

**Comment by nono** [comment]
Yeah, I haven't seen a file with `path: "."` until today.

**Comment by frankrousseau** [comment]
Ok first sync worked fine, until it reuploaded all my pictures. Do you know from where it could come from?

**Comment by nono** [comment]
The files with `path: "."` are handled correctly: cozy-desktop shows an error but keeps the synchronization running. I don't see what we can do better.

For photos from cozy-mobile, we had a regression on how we handle files with no checksum. It should be fixed with #277 and #278.

**Comment by frankrousseau** [comment]
Ok let me know when the new version is out. I will do new tests.

**Comment by nono** [comment]
You can try with the [v0.10.0](https://github.com/cozy-labs/cozy-desktop/releases/tag/v0.10.0) (not yet published on npm)

**Comment by frankrousseau** [comment]
Thx
