### ISSUE TITLE
reproduceable crash on sync resume

### ISSUE THREAD

**Issue by feth** [cozy-labs/cozy-desktop#402]
While resuming sync of my cozy.cc instance to my desktop, I repeatidly get this, at the same point in sync:

```
... [lots of Local watcher] ...
[2016-07-12 22:08:03:332] info - Local watcher  | File added Appareils photo/2014/IMAG1087.jpg
[2016-07-12 22:08:23:368] info - Synchronize    | apply {"id":"Appareils photo/VIDEO0034_0000000000_1.jpg","changes":[{"rev":"3-a4dcb61d29dfd046d0c6d9880724092c"}],"doc":{"path":"Appareils photo/VIDEO0034_0000000000_1.jpg","docType":"file","creationDate":"2015-06-05T20:32:48.000Z","lastModification":"2015-06-05T20:32:48.000Z","remote":{"_id":"f7e192a934377638eb1c6d1f0974aedb","_rev":"4-0f46c84bdd0dc3268d781f2a3883b243","binary":{"_id":"f7e192a934377638eb1c6d1f0974b9d2","_rev":"2-8e7f05b4579e48516623308e96f89359"}},"class":"image","mime":"image/jpeg","tags":["from-Tel_asus"],"localPath":"/storage/MicroSD/DCIM/100MEDIA/VIDEO0034_0000000000_1.jpg","sides":{"remote":3},"_id":"Appareils photo/VIDEO0034_0000000000_1.jpg","_rev":"3-a4dcb61d29dfd046d0c6d9880724092c"},"seq":7913}
[2016-07-12 22:08:23:372] info - Local writer   | Put file /home/feth/cozy/Appareils photo/VIDEO0034_0000000000_1.jpg
[2016-07-12 22:08:23:377] info - Remote CouchDB | Download cozy/f7e192a934377638eb1c6d1f0974b9d2/file
/home/feth/node_modules/cozy-desktop/node_modules/progress/lib/node-progress.js:51
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^

Error: total required
    at new ProgressBar (/home/feth/node_modules/cozy-desktop/node_modules/progress/lib/node-progress.js:51:49)
    at EventEmitter.<anonymous> (/home/feth/node_modules/cozy-desktop/lib/bin/cli.js:76:15)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at /home/feth/node_modules/cozy-desktop/lib/local/index.js:169:32
    at /home/feth/node_modules/cozy-desktop/lib/remote/couch.js:197:16
    at ClientRequest.<anonymous> (/home/feth/node_modules/cozy-desktop/node_modules/request-json-light/main.js:402:14)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
```

I don't know anything about npm. I'm running debian sid.

**Comment by nono** [comment]
Hello,
thanks for the bug report. I'll look at it.

**Comment by feth** [comment]
@nono you can always find me on freenode if needed (feth)
