### ISSUE TITLE
Javascript RangeError

### ISSUE THREAD

**Issue by mariuspo** [cozy-labs/cozy-desktop#426]
I'm getting an error when opening the application since the latest update (package cozy-desktop-gui 0.15.0 in Ubuntu 16.04). The application seems locked and the notification icon is locked in the "Syncing..." mode.

Here's the complete message
Uncaught Exception:
RangeError: Maximum call stack size exceeded
    at Array.indexOf (native)
    at async.eachSeries._this.paths (/opt/cozy-desktop-gui/resources/app.asar/node_modules/cozy-desktop/lib/local/watcher.js:353:45)
    at /opt/cozy-desktop-gui/resources/app.asar/node_modules/async/dist/async.js:3047:20
    at replenish (/opt/cozy-desktop-gui/resources/app.asar/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/opt/cozy-desktop-gui/resources/app.asar/node_modules/async/dist/async.js:869:21)
    at /opt/cozy-desktop-gui/resources/app.asar/node_modules/async/dist/async.js:847:20
    at async.eachSeries._this.paths (/opt/cozy-desktop-gui/resources/app.asar/node_modules/cozy-desktop/lib/local/watcher.js:354:26)
    at /opt/cozy-desktop-gui/resources/app.asar/node_modules/async/dist/async.js:3047:20
    at replenish (/opt/cozy-desktop-gui/resources/app.asar/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/opt/cozy-desktop-gui/resources/app.asar/node_modules/async/dist/async.js:869:21)

**Comment by nono** [comment]
Hello,
it looks like something went wrong. I'll look at this bug this week. Thanks for the bug report!
