### ISSUE TITLE
impossible d'associer un compte sur  cozy-desktop après s'être déconnecté

### ISSUE THREAD

**Issue by leolivier** [cozy-labs/cozy-desktop#445]
Bonjour,
j'ai eu des soucis de lock dans cozy-desktop au démarrage. Après avoir supprimé sans succès les fichiers de log, killé les process, redémarré le PC, j'avais toujours les même problèmes?
En desespoir de compte, je me suis déconnecté et j'ai tenté de recréer mon compte mais impossible. 
Le process va jusqu'au bout (saisie de l'adresse cozycloud, saisie du mdp, saisie du directory de synchro) puis on arrive sur le tableau de bord où j'ai le message : 
![capture du 2016-09-17 12-23-30](https://cloud.githubusercontent.com/assets/4014752/18607597/ada02c86-7cd1-11e6-9365-3eaf92507d27.png)

J'ai essayé 5 fois sans succès. Je me suis deconnecté et reconnecté sur le site web sans problème (je fais des copier coller du mdp depuis keeweb  donc je suis sur que c'est le même...
Contenu des logs
[logs.txt](https://github.com/cozy-labs/cozy-desktop/files/478075/logs.txt)

**Comment by leolivier** [comment]
J'ai un peu regardé les logs côté serveur et je vois de temps :

```
[Sat, 17 Sep 2016 10:15:14 GMT] - POST /request/cozyinstance/all/ - 200 - 27.178 ms -  244
[2016-09-17 10:15:14:316] error - app:error | Application is not authorized
[2016-09-17 10:15:14:317] error - app:error | Error: Application is not authorized
    at /usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/helpers/utils.js:64:13
    at module.exports.checkDocType (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/lib/token.js:60:18)
    at module.exports.checkPermissions (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/helpers/utils.js:58:10)
    at module.exports.checkPermissionsByType (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/middlewares/utils.js:67:10)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/index.js:340:14)
[Sat, 17 Sep 2016 10:15:14 GMT] - POST /request/user/all/ - 403 - 11.874 ms -  41

```
Je ne sais pas si ça a un lien mais ça semble survenir au moment de la tentative de connexion

**Comment by leolivier** [comment]
J'ai un peu regardé les logs côté serveur et je vois de temps :

```
[Sat, 17 Sep 2016 10:15:14 GMT] - POST /request/cozyinstance/all/ - 200 - 27.178 ms -  244
[2016-09-17 10:15:14:316] error - app:error | Application is not authorized
[2016-09-17 10:15:14:317] error - app:error | Error: Application is not authorized
    at /usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/helpers/utils.js:64:13
    at module.exports.checkDocType (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/lib/token.js:60:18)
    at module.exports.checkPermissions (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/helpers/utils.js:58:10)
    at module.exports.checkPermissionsByType (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/build/server/middlewares/utils.js:67:10)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/cozy/apps/data-system/node_modules/cozy-data-system/node_modules/americano/node_modules/express/lib/router/index.js:340:14)
[Sat, 17 Sep 2016 10:15:14 GMT] - POST /request/user/all/ - 403 - 11.874 ms -  41

```
Je ne sais pas si ça a un lien mais ça semble survenir au moment de la tentative de connexion

**Comment by leolivier** [comment]
Je ne comprends pas pourquoi car je n'ai rien fait entre temps sauf regarder les logs. 
J'ai relancé le desktop "pour voir" sans rien faire (pas de reconnexion) et ça a marché :///

J'ai maintenant le message Votre Cozy est à jour!
ci joint les logs serveur : 
[data-system.log.txt](https://github.com/cozy-labs/cozy-desktop/files/478107/data-system.log.txt)
et client : 
[logs.txt](https://github.com/cozy-labs/cozy-desktop/files/478108/logs.txt)

si ça intéresse quelqu'un

**Comment by nono** [comment]
Bonjour,

merci pour ce retour. C'est effectivement anormal que la synchronisation n'ait pas marché du premier coup après la déconnexion. J'ai regardé les logs, mais je ne vois pas vraiment ce qui a buggé. Si le problème se reproduit, on pourra faire quelques tests pour mieux comprendre.
