### ISSUE TITLE
sync crash with "total required" when remote file is empty

### ISSUE THREAD

**Issue by thblt** [cozy-labs/cozy-desktop#452]
```
[2016-09-26 23:11:53:675] info - Local writer   | Put file /home/thblt/.Cozy/Concours/Bouaziz/Episémologie et Logique/C.S. Pierce (comment se fixe la croyance etc.).pdf
[2016-09-26 23:11:53:785] info - Local watcher  | File added Concours/Bouaziz/Courts textes/Section ESTHETIQUE (manuel Terminale).doc
[2016-09-26 23:11:53:856] info - Remote CouchDB | Download cozy/0651d4d45d08dd10055f4f9d2461d096aa7edc4a/file
Downloading C.S. Pierce (comment se fixe la croyance etc.).pdf [==============================] 100% 0.0s
[2016-09-26 23:11:54:26] info - Synchronize    | Applied 2013
[2016-09-26 23:11:54:82] info - Local watcher  | File added Concours/Bouaziz/Courts textes/Section ESTHETIQUE.doc
[2016-09-26 23:11:54:175] info - Synchronize    | apply {"id":"Concours/Bouaziz/MES COURS/COURS L2 2011-2012/POPPER BONNE VERSION.pdf alias","changes":[{"rev":"1-8662b9e55ae71a3abdfb21425885ab93"}],"doc":{"path":"Concours/Bouaziz/MES COURS/COURS L2 2011-2012/POPPER BONNE VERSION.pdf alias","docType":"file","creationDate":"2016-08-05T18:11:36.537Z","lastModification":"2016-04-08T10:41:13.620Z","remote":{"_id":"2db38fdf0a5a489695d5c6c8187bbef8","_rev":"1-ac79035c5a066d6324c90f32d35f8f88","binary":{"_id":"da39a3ee5e6b4b0d3255bfef95601890afd80709","_rev":"4-b68530aca289e088a390ba6f4e129b98"}},"checksum":"da39a3ee5e6b4b0d3255bfef95601890afd80709","class":"document","mime":"application/octet-stream","tags":[],"sides":{"remote":1},"_id":"Concours/Bouaziz/MES COURS/COURS L2 2011-2012/POPPER BONNE VERSION.pdf alias","_rev":"1-8662b9e55ae71a3abdfb21425885ab93"},"seq":2014}
[2016-09-26 23:11:54:175] info - Local writer   | Put file /home/thblt/.Cozy/Concours/Bouaziz/MES COURS/COURS L2 2011-2012/POPPER BONNE VERSION.pdf alias
[2016-09-26 23:11:54:310] info - Remote CouchDB | Download cozy/da39a3ee5e6b4b0d3255bfef95601890afd80709/file
/usr/lib/node_modules/cozy-desktop/node_modules/progress/lib/node-progress.js:51
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^

Error: total required
    at new ProgressBar (/usr/lib/node_modules/cozy-desktop/node_modules/progress/lib/node-progress.js:51:49)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/cozy-desktop/lib/bin/cli.js:76:15)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at /usr/lib/node_modules/cozy-desktop/lib/local/index.js:169:32
    at /usr/lib/node_modules/cozy-desktop/lib/remote/couch.js:197:16
    at ClientRequest.<anonymous> (/usr/lib/node_modules/cozy-desktop/node_modules/request-json-light/main.js:402:14)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
```

(Looks like I'm good to trigger nasty bugs)

**Comment by thblt** [comment]
The file seems to be a zero bytes macOs alias file. All involved machines are running Linux, so no dark macOs magic should be involved.

**Comment by thblt** [comment]
Same bug with another zero bytes file

```
[2016-09-26 23:20:10:208] info - Synchronize    | apply {"id":"Concours/Bouaziz/MES COURS/Yatil des RA TEX/Yatildesreglesdelart.bbl","changes":[{"rev":"1-ca226212ce
e07b5c49b531b43fd3e97c"}],"doc":{"path":"Concours/Bouaziz/MES COURS/Yatil des RA TEX/Yatildesreglesdelart.bbl","docType":"file","creationDate":"2016-08-05T18:11:36.537Z","lastModification":"2016-04-08T10:41:50.235Z","remote":{"_id":"d632c404d18d4270aa2993719aa9565e","_rev":"1-6078b80808f61e386f3a57557956c16d","binary":{"_id":"da39a3ee5e6b4b0d3255bfef95601890afd80709","_rev":"4-b68530aca289e088a390ba6f4e129b98"}},"checksum":"da39a3ee5e6b4b0d3255bfef95601890afd80709","class":"document","mime":"application/octet-stream","tags":[],"sides":{"remote":1},"_id":"Concours/Bouaziz/MES COURS/Yatil des RA TEX/Yatildesreglesdelart.bbl","_rev":"1-ca226212cee07b5c49b531b43fd3e97c"},"seq":2018}
[2016-09-26 23:20:10:209] info - Local writer   | Put file /home/thblt/.Cozy/Concours/Bouaziz/MES COURS/Yatil des RA TEX/Yatildesreglesdelart.bbl
[2016-09-26 23:20:10:374] info - Remote CouchDB | Download cozy/da39a3ee5e6b4b0d3255bfef95601890afd80709/file
/usr/lib/node_modules/cozy-desktop/node_modules/progress/lib/node-progress.js:51
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^

Error: total required
    at new ProgressBar (/usr/lib/node_modules/cozy-desktop/node_modules/progress/lib/node-progress.js:51:49)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/cozy-desktop/lib/bin/cli.js:76:15)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at /usr/lib/node_modules/cozy-desktop/lib/local/index.js:169:32
    at /usr/lib/node_modules/cozy-desktop/lib/remote/couch.js:197:16
    at ClientRequest.<anonymous> (/usr/lib/node_modules/cozy-desktop/node_modules/request-json-light/main.js:402:14)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
```

**Comment by nono** [comment]
Hi @thblt,

can you try the git master version? I've just pushed 4cbc222ec365cb81bd1ba2cb083cca9dcf8811b9, and it should fix this issue.

**Comment by thblt** [comment]
Sure but... I don't know the Good Way to do this with node :-) `npm install -g cozy-desktop@master`, or `git clone` and `npm link`/`npm install` ? Something else? 

Thanks!

**Comment by nono** [comment]
You can go the manual way:

```
git clone git@github.com:cozy-labs/cozy-desktop.git
cd cozy-desktop
npm i
npm run build
./bin/cozy-desktop sync
```

If it works well, I will publish a new version on npm.

**Comment by thblt** [comment]
Thanks! I'll try to do this next Sunday.  Sorry for being a bit slow, but I don't have much time these days :-)

**Comment by nono** [comment]
Don't worry, there is no urgency. This bug is only on the CLI version of cozy-desktop, not the GUI (else, we would have spot it sooner). Thank you for taking time to improve cozy-desktop!

**Comment by feth** [comment]
Hello @nono ,
Hit the same problem; looks like your 4cbc222 is fixing it!
Thx!
