### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by aenario** [cozy-labs/cozy-desktop#71]
So just tried this on windows and there is 1 or 2 errors : 
#1 - Download & reupload

Not sure if this an error, but when i firs sync my folder (local empty), I have :

```
info - Queue          | Missing file detected: C:\Users\Romain\cozy-synced\YOLO57\cozy_attaque_56.png
info - Filesystem     | Downloading: C:\Users\Romain\cozy-synced\YOLO57\cozy_attaque_56.png...
info - Filesystem     | Binary downloaded: C:\Users\Romain\cozy-synced\YOLO57\cozy_attaque_56.png
info - Queue          | Creating unlisted folders remotely...
info - Queue          | Uploading modifications to remote...
info - Pouch/CouchDB  | Changes replicated to remote
info - Queue          | New file detected: C:\Users\Romain\cozy-synced\YOLO57\cozy_attaque_56.png
info - Pouch/CouchDB  | Uploading binary: C:\Users\Romain\cozy-synced\YOLO57\cozy_attaque_56.png...
info - Pouch/CouchDB  | Binary uploaded: C:\Users\Romain\cozy-synced\YOLO57\cozy_attaque_56.png
info - Remote watcher | All your files are now available on your device.
info - Pouch/CouchDB  | Changes replicated to remote
```

The result is OK, althought. 
#2 - Paths

```
info - Local watcher  | File changed: C:\Users\Romain\cozy-synced\C:\Users\Romain\cozy-synced\BEBOPALLULA.txt
error - Queue          | An error occured during the operation updateFileRemotely:
Error: C:\Users\Romain\cozy-synced\C:\Users\Romain\cozy-synced\BEBOPALLULA.txt does not exist
    at c:\Users\Romain\Projects\cozy-desktop\backend\filesystem.js:107:27
    at Object.cb [as oncomplete] (fs.js:168:19)
info - Pouch/CouchDB  | Changes replicated to remote
```

(seems like an absolute path considered relative)
and a minute later : 

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (c:\Users\Romain\Projects\cozy-desktop\node_modules\pouchdb\lib\deps\ajax.js:156:19)
    at Request.self.callback (c:\Users\Romain\Projects\cozy-desktop\node_modules\pouchdb\node_modules\request\request.js:123:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (c:\Users\Romain\Projects\cozy-desktop\node_modules\pouchdb\node_modules\request\request.js:877:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (c:\Users\Romain\Projects\cozy-desktop\node_modules\pouchdb\node_modules\request\request.js:828:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by nono** [comment]
We have some an alpha version for windows -> https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.0.0-alpha3
